CREATE DATABASE EMPLOYEE;

USE EMPLOYEE;
CREATE TABLE COUNTRIES_HR_DATA (
COUNTRY_ID VARCHAR (20) PRIMARY KEY,
COUNTRY_NAME TEXT NOT NULL,
REGION_ID INT NOT NULL);

SELECT * FROM COUNTRIES_HR_DATA

CREATE TABLE JOBS_HR_DATA (
JOB_ID VARCHAR (10) PRIMARY KEY,
JOB_TITLE TEXT NOT NULL,
MIN_SALARY INT NOT NULL,
MAX_SALARY INT NOT NULL);

SELECT * FROM JOBS_HR_DATA

CREATE TABLE EMPLOYEE_HR_DATA (
EMPLOYEE_ID INT PRIMARY KEY,
FIRST_NAME TEXT NOT NULL,
LAST_NAME TEXT NOT NULL,
EMAIL TEXT NOT NULL,
PHONE_NUMBER TEXT NOT NULL,
HIRE_DATE DATE NOT NULL,
JOB_ID TEXT NOT NULL,
SALARY INT NOT NULL,
COMMISSION_PCT INT NOT NULL,
MANAGER_ID INT NOT NULL,
DEPARTMENT_ID INT NOT NULL);

SELECT * FROM EMPLOYEE_HR_DATA

CREATE TABLE LOCATION_HR_DATA (
LOCATION_ID INT PRIMARY KEY,
STREET_ADDRESS VARCHAR (60),
POSTAL_CODE VARCHAR (40),
CITY TEXT,
STATE_PROVINCE TEXT,
COUNTRY_ID VARCHAR (40) NOT NULL
);

SELECT * FROM LOCATION_HR_DATA

CREATE TABLE DEPARTMENT_HR_DATA (
DEPARTMENT_ID INT PRIMARY KEY,
DEPARTMENT_NAME TEXT NOT NULL,
MANAGER_ID INT,
LOCATION_ID INT,
FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION_HR_DATA (LOCATION_ID));

SELECT * FROM DEPARTMENT_HR_DATA

CREATE TABLE JOB_HISTORY_HR_DATA (
EMPLOYEE_ID INT,
FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE_HR_DATA (EMPLOYEE_ID),
START_DATE DATE NOT NULL,
END_DATE DATE NOT NULL,
JOB_ID VARCHAR (40) NOT NULL,
DEPARTMENT_ID INT);

CREATE TABLE JOB_GRADES_HR_DATA (
GRADE_LEVEL TEXT NOT NULL,
LOWEST_SAL INT NOT NULL,
HIGHEST_SAL INT NOT NULL);

SELECT * FROM JOB_GRADES_HR_DATA


-- Q.1
SELECT FIRST_NAME,LAST_NAME,DEPARTMENT_ID,SALARY
FROM EMPLOYEE_HR_DATA
WHERE SALARY>9000



-- Q.2
SELECT * FROM EMPLOYEE_HR_DATA
WHERE DEPARTMENT_ID=0


-- Q.3
SELECT CONCAT (FIRST_NAME,'',LAST_NAME) AS "FULL_NAME",HIRE_DATE,SALARY,DEPARTMENT_ID
FROM EMPLOYEE_HR_DATA
WHERE FIRST_NAME NOT LIKE '%T%'




-- Q.4
SELECT * FROM EMPLOYEE_HR_DATA
WHERE SALARY >= 9000 AND SALARY <= 12000




-- Q.5
SELECT CONCAT (FIRST_NAME,'',LAST_NAME) AS FULL_NAME,SALARY
FROM EMPLOYEE_HR_DATA
WHERE COMMISSION_PCT=0.00


-- Q.6
SELECT CONCAT (FIRST_NAME,'',LAST_NAME) AS FULL_NAME,SALARY,MANAGER_ID
FROM EMPLOYEE_HR_DATA
WHERE MANAGER_ID >0




-- Q.7
SELECT * FROM EMPLOYEE_HR_DATA
WHERE FIRST_NAME LIKE '%T%' OR FIRST_NAME LIKE '%M%' OR FIRST_NAME LIKE '%M%'
ORDER BY SALARY DESC



-- Q.8
SELECT CONCAT (FIRST_NAME,'',LAST_NAME) AS FULL_NAME,HIRE_DATE,COMMISSION_PCT,EMAIL,'-',PHONE_NUMBER,SALARY
FROM EMPLOYEE_HR_DATA
WHERE SALARY >12000 OR PHONE_NUMBER LIKE '______3%'
ORDER BY FIRST_NAME DESC


-- Q.9
SELECT FIRST_NAME,LAST_NAME,DEPARTMENT_ID
FROM EMPLOYEE_HR_DATA
WHERE FIRST_NAME LIKE '__S%'


-- Q.10
SELECT EMPLOYEE_ID
FROM JOB_HISTORY_HR_DATA
GROUP BY EMPLOYEE_ID
HAVING COUNT(*)>=2

-- Q.11
SELECT JOB_ID, COUNT(EMPLOYEE_ID),SUM(SALARY),MAX(SALARY)-MIN(SALARY) AS SALARY_DIFFERENCE
FROM EMPLOYEE_HR_DATA
GROUP BY JOB_ID

-- Q.12
SELECT JOB_ID
FROM JOB_HISTORY_HR_DATA
WHERE END_DATE - START_DATE >300
GROUP BY JOB_ID
HAVING COUNT(*)>1

-- Q.13
SELECT MANAGER_ID,COUNT(EMPLOYEE_ID) AS NO_OF_EMPLOYEE
FROM EMPLOYEE_HR_DATA
GROUP BY MANAGER_ID

-- Q.14
SELECT DEPARTMENT_ID, AVG(SALARY)
FROM EMPLOYEE_HR_DATA
WHERE COMMISSION_PCT IS NOT NULL
GROUP BY DEPARTMENT_ID

-- Q.15
SELECT DEPARTMENT_ID
FROM EMPLOYEE_HR_DATA
WHERE COMMISSION_PCT IS NOT NULL
GROUP BY DEPARTMENT_ID
HAVING COUNT(EMPLOYEE_ID)>10

-- Q.16	
SELECT JOB_TITLE, MAX_SALARY, MIN_SALARY
FROM JOBS_HR_DATA
WHERE MAX_SALARY BETWEEN 10000 AND 15000	

-- Q.17
SELECT * FROM JOBS_HR_DATA
WHERE MIN_SALARY > 9000


-- Q.18
SELECT FIRST_NAME,LAST_NAME,HIRE_DATE
FROM EMPLOYEE_HR_DATA
WHERE DEPARTMENT_ID =
( SELECT DEPARTMENT_ID 
FROM EMPLOYEE_HR_DATA
WHERE FIRST_NAME LIKE '%CLARA%')
AND FIRST_NAME NOT LIKE '%CLARA%'

-- Q.19
SELECT EMPLOYEE_ID,FIRST_NAME,SALARY
FROM EMPLOYEE_HR_DATA
WHERE 1 = 1
AND SALARY > 
(SELECT AVG(SALARY) FROM EMPLOYEE_HR_DATA)
AND DEPARTMENT_ID IN
( SELECT DEPARTMENT_ID
FROM EMPLOYEE_HR_DATA
WHERE FIRST_NAME LIKE '%J%');

-- Q.20
SELECT EMPLOYEE_ID,CONCAT(FIRST_NAME,'',LAST_NAME) AS NAME, JOB_ID,
CASE TRIM(JOB_ID)
WHEN 'ST_MAN' THEN 'SALESMAN'
WHEN 'IT_PROG' THEN 'DEVELOPER'
ELSE JOB_ID
END AS DESIGNATION, SALARY
FROM EMPLOYEE_HR_DATA;

-- JOINS

-- Q.1
SELECT A.FIRST_NAME,A.LAST_NAME,B.DEPARTMENT_NAME,C.CITY,C.STATE_PROVINCE
FROM EMPLOYEE_HR_DATA A
JOIN DEPARTMENT_HR_DATA B
ON A.DEPARTMENT_ID = B. DEPARTMENT_ID
JOIN LOCATION_HR_DATA C
ON B.LOCATION_ID = C.LOCATION_ID


-- Q.2
SELECT A.FIRST_NAME, A.LAST_NAME, A.SALARY, B.GRADE_LEVEL
FROM EMPLOYEE_HR_DATA A
JOIN JOB_GRADES_HR_DATA B
ON A.SALARY BETWEEN B.LOWEST_SAL AND B.HIGHEST_SAL

-- Q.3
SELECT A.FIRST_NAME, A.LAST_NAME, B.DEPARTMENT_NAME, A.DEPARTMENT_ID
FROM EMPLOYEE_HR_DATA A
JOIN DEPARTMENT_HR_DATA B
ON A.DEPARTMENT_ID = B.DEPARTMENT_ID
AND A.DEPARTMENT_ID IN (80,40)
ORDER BY A.LAST_NAME

-- Q.4
SELECT A.FIRST_NAME, A.LAST_NAME, C.DEPARTMENT_NAME, B.CITY, B.STATE_PROVINCE
FROM DEPARTMENT_HR_DATA C
JOIN EMPLOYEE_HR_DATA A 
ON A.DEPARTMENT_ID = C.DEPARTMENT_ID
JOIN LOCATION_HR_DATA B
ON C.LOCATION_ID = B.LOCATION_ID
AND FIRST_NAME LIKE '%Z%'

-- Q.5
SELECT CONCAT(A.FIRST_NAME,'',A.LAST_NAME) AS EMPLOYEE_NAME, A.JOB_ID, B.START_DATE
FROM EMPLOYEE_HR_DATA A
JOIN JOB_HISTORY_HR_DATA B
ON A.EMPLOYEE_ID = B.EMPLOYEE_ID
WHERE START_DATE>='1993-01-01' AND START_DATE<='1997-08-31'


-- Q.6
SELECT B.JOB_TITLE, CONCAT(A.FIRST_NAME,'',A.LAST_NAME) AS EMPLOYEE_NAME, B.MAX_SALARY - A.SALARY AS SALARY_DIFFERENCE
FROM EMPLOYEE_HR_DATA A
NATURAL JOIN JOBS_HR_DATA B
WHERE DEPARTMENT_ID = 80;


-- Q.7 INSTEAD OF MANAGER USING EMPLOYEE
SELECT A.DEPARTMENT_NAME, CONCAT(B.FIRST_NAME,'',B.LAST_NAME) AS MANAGER_NAME
FROM DEPARTMENT_HR_DATA A
JOIN EMPLOYEE_HR_DATA B
ON A.MANAGER_ID = B.EMPLOYEE_ID


-- Q.8 
SELECT A.DEPARTMENT_NAME, CONCAT(B.FIRST_NAME,'',B.LAST_NAME) AS MANAGER_NAME, C.CITY
FROM DEPARTMENT_HR_DATA A
JOIN EMPLOYEE_HR_DATA B
ON A.MANAGER_ID = B.EMPLOYEE_ID
JOIN LOCATION_HR_DATA C
ON A.LOCATION_ID = C.LOCATION_ID


-- Q.9
SELECT A.DEPARTMENT_NAME, CONCAT(B.FIRST_NAME,'',B.LAST_NAME) AS MANAGER_NAME, D.COUNTRY_NAME
FROM DEPARTMENT_HR_DATA A
JOIN EMPLOYEE_HR_DATA B
ON A.DEPARTMENT_ID = B.DEPARTMENT_ID
JOIN LOCATION_HR_DATA C
ON A.LOCATION_ID = C.LOCATION_ID
JOIN COUNTRIES_HR_DATA D
ON C.COUNTRY_ID = D.COUNTRY_ID